<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddressCountryTable extends Doctrine_Table
{
	static public function retrieveByText($name='United States'){
		$query = Doctrine_Query::create();
		
		$query->from('AddressCountry a');
		$query->where('a.name = ?', $name);		
		$result = $query->fetchOne();
		return $result;
	}	
}