<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddressStateTable extends Doctrine_Table
{

  static function retrieveByText($str)
	{
    
    $q = Doctrine_Query::create()
          ->from('AddressState s')
          ->where('s.abbreviation = ? OR s.name = ?', array($str, $str))
          ->fetchOne();
          
         
    return $q;
    
	}

}