<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AliasTable extends Doctrine_Table
{
  static function getByEntityId($id, $context=null)
  {
    $db = LsDb::getDbConnection();
    $sql = "SELECT name FROM alias WHERE entity_id = ?";
    $params = array($id);

    if ($context) 
    { 
      $sql .= " AND context = ?";
      $params[] = $context;
    }
    elseif ($context === false)
    {
      $sql .= " AND context IS NULL";
    }
    
    $stmt = $db->execute($sql, $params);

    return $stmt->fetchAll(PDO::FETCH_COLUMN);
  }
}