<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiUser extends BaseApiUser
{
  public function generateKey()
  {
    if (!$this->email)
    {
      throw new Exception("Can't generate key with empty email field");
    }
  
    do
    {
      $key = sha1($this->email . mt_rand() . microtime(true));
      
      $db = Doctrine_Manager::connection();
      $sql = 'SELECT COUNT(*) FROM api_user u WHERE u.api_key = ?';
      $stmt = $db->execute($sql, array($key));
      $result = (int) $stmt->fetch(PDO::FETCH_COLUMN);
    } 
    while ($result != 0);
    
    return $key;
  } 
  
  
  public function getFullName()
  {
    return $this->name_first . ' ' . $this->name_last;
  }
}