<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DegreeTable extends Doctrine_Table
{
  static public function getByText($text)
  {
    return Doctrine_Query::create()
      ->from('Degree d')
      ->where('d.name = ? OR d.abbreviation = ?', array($text, $text))
      ->fetchOne();
  }

  static public function addDegree($name, $abbreviation = null)
	{
    
    $name = trim($name);
    $abbreviation = trim($abbreviation);
    

    if( self::getByText($name) || self::getByText($abbreviation) )
    {
      return false;
    }
     

    $degree = new Degree;
    $degree->name = $name;
    $degree->abbreviation = $abbreviation;
    $degree->save();
    
    return self::getByText($name);
     
    
  }
}