<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailTable extends Doctrine_Table
{
  static function isEmail($str)
  {
    return (bool) preg_match('/^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i', $str);  
  }
}