<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtensionRecord extends BaseExtensionRecord
{
  public function getName()
  {
    return get_class($this) . ' ' . $this->id;
  }
}
