<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FamilyTable extends Doctrine_Table
{

  static $relations_hash = array(
    array('father','daughter',GenderTable::MALE),
    array('father', 'son',GenderTable::MALE),
    array('mother', 'daughter',GenderTable::FEMALE),
    array('mother', 'son',GenderTable::FEMALE),
    array('son', 'mother',GenderTable::MALE),
    array('son', 'father',GenderTable::MALE),
    array('daughter', 'mother',GenderTable::FEMALE),
    array('daughter', 'father',GenderTable::FEMALE),
    array('brother', 'sister',GenderTable::MALE),
    array('brother', 'brother',GenderTable::MALE),
    array('sister', 'brother',GenderTable::FEMALE),
    array('sister', 'sister',GenderTable::FEMALE),
    array('uncle', 'nephew',GenderTable::MALE),
    array('uncle', 'niece',GenderTable::MALE),
    array('aunt', 'nephew',GenderTable::FEMALE),
    array('aunt', 'niece',GenderTable::FEMALE),
    array('cousin', 'cousin',GenderTable::FEMALE),
    array('cousin', 'cousin',GenderTable::MALE),
    array('husband', 'wife',GenderTable::MALE),
    array('wife', 'husband',GenderTable::FEMALE),
    array('mother', 'daughter',GenderTable::FEMALE),
    array('grandmother', 'granddaughter',GenderTable::FEMALE),
    array('grandmother', 'grandson',GenderTable::FEMALE));
    
  static $generic_relations = array(
    'sibling' => array('brother','sister'),
    'spouse' => array('husband','wife'),
    'child' => array('mother','father'),
    'parent' => array('son','daughter'),
    'cousin' => array('cousin'));

  static function getDescription2($description1,$gender2_id)
  {
    $description1 = strtolower($description1);

    foreach (self::$relations_hash as $r)
    {
      if ($r[1] == $description1 && $r[2] == $gender2_id)
      {
        return $r[0];
      }
    }
    
    foreach (self::$generic_relations as $k => $v)
    {
      if (in_array($description1, $v))
      {
        return $k;
      }
    }
    
    return false;
  }

}