<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Family extends BaseFamily
{
  public function getDetails()
  {
    if ($this->is_nonbiological)
    {
      return 'non-biological';
    }
    
    return null;
  }
}