<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FecFilingTable extends Doctrine_Table
{

    static public function getFecFiling($record_id){
            $query = Doctrine_Query::create();
            
            $query->from('FecFiling f');
            $query->where('f.fec_filing_id = ?', $record_id);               
            return $query->fetchOne();
    }       
        

  static function generateUniqueKey($filing)
  {
    return implode('/', array(
      $filing['relationship_id'],
      $filing['crp_cycle'],
      $filing['crp_id'],
      $filing['fec_filing_id'],
      $filing['amount'],
      $filing['start_date']
    ));
  }  
}

