<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FecFiling extends BaseFecFiling
{
  public function getSourceUrl()
  {
    if (!$fecId = $this->fec_filing_id)
    {
      return null;
    }
  
    return 'http://images.nictusa.com/cgi-bin/fecimg/?' . $fecId;
  }

  public function getFecDonations()
  {
    
    return Doctrine_Query::create()
          ->from('Donation d')
          ->where('d.relationship_id', array($this->id))
          ->execute();
    
  }
}
