<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FedspendingFilingTable extends Doctrine_Table
{
  static public function getByFedspendingId($id)
  {
    $q = Doctrine_Query::create()
      ->from('FedspendingFiling f')
      ->where('f.fedspending_id = ?', $id);    

    return $q->fetchOne();
  }  
}