<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Image extends BaseImage
{

  protected $_isMerge = false;


  public function setMerge($bool)
  {
    $this->_isMerge = (bool) $bool;
  }
  

  public function isMerge()
  {
    return $this->_isMerge;
  }
  
  public function getProfilePath()
  {
    return ImageTable::getPath($this, 'profile');
  }

  public function getLargePath()
  {
    return ImageTable::getPath($this, 'large');
  }

  public function getSmallPath()
  {
    return ImageTable::getPath($this, 'small');
  }
  
  public function getInternalUrl()
  {
    return ImageTable::getInternalUrl($this);
  }
}