<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Industry extends BaseIndustry
{

    
  public function getDisplayName()
  {

    if ($this->context == 'SIC' && $this->code)
    {
      $display = '<a href="http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&SIC=' . $this->code . '&owner=only&count=100">' . $this->name . ' (SIC - ' . $this->code . ')</a>';
    }
    else if ($this->code && $this->context)
    {
      $display = $this->name . ' (' . $this->context . ' - ' . $this->code . ')';
    }
    else
    {
      $display = $this->name;
    }
    
    return $display;
  }

}