<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkTable extends Doctrine_Table
{
  static function getRelationshipIdsBetween($id1, $id2, $categoryIds=null)
  {
    $db = Doctrine_Manager::connection();

    $q = LsDoctrineQuery::create()
      ->select('l.relationship_id')
      ->from('Link l')
      ->where('l.entity1_id = ? AND l.entity2_id = ?', array($id1, $id2));
    
    if ($categoryIds)
    {
      $q->andWhereIn('l.category_id', (array) $categoryIds);
    }
    
    return $db->execute($q->getSqlQuery(), $q->getParams())->fetchAll(PDO::FETCH_COLUMN | PDO::FETCH_UNIQUE, 1);
  }
}