<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LobbyFiling extends BaseLobbyFiling
{
  public function getAgenciesQuery()
  {
    return LobbyFilingTable::getAgenciesQuery($this);
  }
  
  public function getSourceUrl()
  {
    return LobbyFilingTable::getSourceUrl($this);
  }
  
  public function getClientQuery()
  {
    $q = LsDoctrineQuery::create()
      ->from('Entity e')
      ->leftJoin('e.Relationship r ON (e.id = r.entity1_id)')
      ->leftJoin('r.LobbyFilingRelationship lfr')
      ->where('lfr.lobby_filing_id = ? AND r.category_id = ?', array($this->id, RelationshipTable::TRANSACTION_CATEGORY));
      
    return $q;
  }
}