<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Membership extends BaseMembership
{
  public function getDetails()
  {
    if ($this->dues)
    {
      return 'dues: ' . $this->dues;
    }
  }
}