<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Modification extends BaseModification
{
  public function getType()
  {
    return ModificationTable::getType($this);
  }
  
  
  public function getName()
  {
    return ModificationTable::getName($this);
  }
}