<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModificationTable extends Doctrine_Table
{
  static function getByUserIdGroupedByObject($userId)
  {
    return LsDoctrineQuery::create()
      ->from('Modification m')
      ->where('m.user_id = ?', $userId)
      ->groupBy('m.object_model, m.object_id')
      ->execute();  
  }
  
  static function getWatchersQuery($object)
  {
  
    $q = LsDoctrineQuery::create()
        ->select('u.*, count(m.id) AS mods')
        ->from('sfGuardUser u')
        ->leftJoin('u.Modification m')
        ->where('m.object_model = ? and m.object_id = ?', array(get_class($object), $object->id))
        ->groupBy('u.id')
        ->orderBy('mods DESC');

    return $q;
  }


  static function getType($modification)
  {
    if ($modification['is_create'])
    {
      return 'create';
    }
    elseif ($modification['is_merge'])
    {
      return 'merge';
    }
    elseif ($modification['is_delete'])
    {
      return 'delete';
    }
    else
    {
      return 'update';
    }
  }  

  
  static function getName($modification)
  {
    return $modification['object_name'] ? $modification['object_name'] : $modification['object_model'] . ' ' . $modification['object_id'];  
  }
}