<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjectTag extends BaseObjectTag
{
  public function getObject()
  {
    return Doctrine::getTable($this->object_model)->find($this->object_id);  
  }
  
  
  public function setObject(Doctrine_Record $record)
  {
    if (!$record->exists())
    {
      throw new Exception("Can't set ObjectTag's object to new object");
    }


    $this->object_model = get_class($record);
    $this->object_id = $record->id;  
  }
}