<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ownership extends BaseOwnership
{
  public function getDetails()
  {
    $details = array();
    
    if ($this->percent_stake)
    {
      $details[] = $this->percent_stake . '% stake';
    }
    
    if ($this->shares)
    {
      $details[] = LsNumber::makeReadable($this->shares) . ' shares';
    }
    
    return implode(', ', $details);
  }
}