<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhoneTable extends Doctrine_Table
{
	static $types = array( 
		0 => 'work',
		1 => 'home',  
		2 => 'mobile',
		3 => 'work fax',
		4 => 'home fax',
		5 => 'other',
		6 => 'phone', 
		7 => 'fax');
  
  static function formatForDb($str)
  {
    $str = preg_replace('/\D/', '', $str);
    
    switch (strlen($str))
    {
      case 10:
        return $str;
        
      case 11:
        if ($str[0] == '1')
        {
          return $str;
        }
        break;
        
      default:
        return null;
    }
  }
}