<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Phone extends BasePhone
{

  protected $_isMerge = false;


  public function setMerge($bool)
  {
    $this->_isMerge = (bool) $bool;
  }
  

  public function isMerge()
  {
    return $this->_isMerge;
  }
  
  public function __toString()
  {
    $str = substr($this->number, 0, 3) . '.' . substr($this->number, 3, 3) . '.' . substr($this->number, 6, 4);
    
    if ($this->type != 'phone')
    {
      $str .= ' (' . $this->type . ')';
    }
    
    return $str;
  }
}