<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PoliticalDistrictTable extends Doctrine_Table
{

  static function getFederalDistrict($state, $district)
	{        
	  return Doctrine_Query::create()
          ->from('PoliticalDistrict p')
          ->leftJoin('p.State s')
          ->where('(s.abbreviation = ? OR s.name = ?  ) AND p.federal_district = ?', array(trim($state), trim($state), trim($district) ) )
          ->fetchOne();
    
	}

  
  static function getStateDistrict()
	{
	}

  static function getLocalDistrict()
	{
	}

  static function addFederalDistrict($state_name, $federal_district)
	{
    
    $state_name = trim($state_name);
    $federal_district = trim($federal_district);
    
    $exists = self::getFederalDistrict($state_name, $federal_district);

    if( $exists != false ){
      //echo "it exists;";
      return false;
    }
     
    $state = null;
    
    $state = AddressStateTable::retrieveByText($state_name);
    
    if(!$state){
      throw new Exception("AddressStateTable did not return state");
    }

    if($state && strlen($federal_district)){
      $district = new PoliticalDistrict;
      $district->State = $state;
      $district->federal_district = $federal_district;
      $district->save();
    }

    return self::getFederalDistrict($state_name, $federal_district);
     
    
  }
 
  
  static function addStateDistrict()
  {
  
  }

  static function addLocalDistrict()
  {
  
  }
  
}