<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PoliticalFundraisingTypeTable extends Doctrine_Table
{
	static public function retrieveByText($name){
		$query = Doctrine_Query::create();
		
		$query->from('PoliticalFundraisingType p');
		$query->where('p.name = ?', $name);		
		$result = $query->fetchOne();
		return $result;
	}
}