<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PoliticalCandidateTable extends Doctrine_Table
{
  static function getFecFieldByFecId($fecId)
  {
    $map = array('H' => 'house_fec_id', 'S' => 'senate_fec_id', 'P' => 'pres_fec_id');
    
    if ($ret = $map[substr($fecId, 0, 1)])
    {
      return $ret;
    }
    
    return null;
  }
}