<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PositionTable extends Doctrine_Table
{
  static $boardTitles = array(
    'Chairman',
    'Chairperson',
    'Chairwoman',
    'Chair',
    'Chairman of the Board',
    'Board Chair',
    'Board Chairman',
    'Vice Chairman',
    'Vice Chairman of the Board',
    'Vice Chair',
    'Co-Chairman',
    'Co-Chair',
    'Co-Chairman of the Board'
  );

  static $businessPositions = array(
    'Adjunct Professor',
    'Administrator',
    'Advisor',
    'Advisory Director',
    'Assistant Secretary',
    'Assistant Treasurer',
    'Associate',
    'Board Member',
    'Branch Manager',
    'Chairman of the Advisory Board',
    'Chairman of the Board',
    'Chairman',
    'Chairman of the Board of Trustees',
    'Chairperson',
    'Chancellor',
    'Chief Accounting Officer',
    'Chief Accounting Officer',
    'CAO',
    'Chief Administrative Officer',
    'Chief Administrative Officer',
    'CAO',
    'Chief Business Officer',
    'CBO',
    'Chief Compliance Officer',
    'Chief Executive Officer',
    'CEO',
    'Chief Financial Officer',
    'CFO',
    'Chief Information Officer',
    'CIO',
    'Chief Investment Officer',
    'CIO',
    'Chief Legal Officer',
    'Chief Legal Officer',
    'CLO',
    'Chief of Staff',
    'Chief Operating Officer',
    'COO',
    'Chief Technical Officer',
    'CTO',
    'Chief Technology Officer',
    'CTO',
    'City Clerk',
    'City Comptroller',
    'Co-Chairman',
    'Co-Chair',
    'Co-Chief Executive Officer',
    'Co-CEO',
    'Co-Chief Operating Officer',
    'Co-COO',
    'Co-Founder',
    'Co-President',
    'Co-Pres',
    'Commissioner of Assessment and Taxation',
    'Commissioner of Economic Development',
    'Comptroller',
    'Consultant',
    'Controller',
    'Corporate Advisory Board Member',
    'Counsel',
    'Dean',
    'Deputy Chairman of the Board',
    'Deputy Chairman',
    'Deputy Mayor',
    'Director',
    'Dir',
    'Director of Communications',
    'Director of Fundraising',
    'Director of Planning',
    'Director of Public Affairs',
    'District President',
    'Division President',
    'Ex-Officio Member',
    'Executive',
    'Executive Advisor',
    'Executive Chairman of the Board',
    'Executive Chairman',
    'Executive Dean of Administration',
    'Executive Director',
    'Exec Dir',
    'Executive Officer',
    'Executive Vice President',
    'EVP',
    'Executive Vice President (Finance)',
    'Fellow',
    'Finance Commissioner',
    'Founder',
    'General Counsel',
    'Gen Counsel',
    'General Partner',
    'Group Vice President',
    'International Specialist',
    'Investment & Debt Management Officer',
    'Lobbyist',
    'Managing Director',
    'Managing Editor',
    'Managing Partner',
    'Member of the Advisory Board',
    'Advisory Board Member',
    'Member of the Board of Governors',
    'Non-Executive Chairman of the Board',
    'Non-Executive Chairman',
    'Non-executive Director',
    'Overseer',
    'Owner',
    'Partner',
    'President',
    'Pres',
    'President Elect',
    'Principal',
    'Principal Deputy General Counsel',
    'Principal Executive Officer',
    'Professor',
    'Program Director',
    'Provost',
    'Publisher',
    'Regional President',
    'Research Director',
    'Secretary',
    'Senior Advisor',
    'Senior Chairman',
    'Sr Chairmain',
    'Senior Consultant',
    'Senior Director',
    'Senior Executive Vice President',
    'Senior EVP',
    'Senior Fellow',
    'Senior Managing Director',
    'Senior Partner',
    'Senior Policy Advisor',
    'Senior Vice Chairman',
    'Sr Vice Chairman',
    'Senior Vice President',
    'SVP',
    'Special Advisor',
    'Staff Attorney',
    'Treasurer',
    'Trustee',
    'Vice Chairman',
    'Vice Chair',
    'Vice Chairman of Corporate Development',
    'Vice Chairman of the Advisory Board',
    'Vice Chairman of the Board',
    'Vice Chairman',
    'Vice Chairperson',
    'Vice President',
    'VP',
    'Vice President of Operations',
    'Visitor',
    'Volunteer'
  );


  static function getDisplayDescription($relationship=null)
  {
    if ($relationship && ($desc = $relationship['description1']))
    {
      return $desc;
    }

    $db = Doctrine_Manager::connection();
    $sql = 'SELECT * FROM position WHERE relationship_id = ? LIMIT 1';
    $stmt = $db->execute($sql, array($relationship['id']));
    $position = $stmt->fetch(PDO::FETCH_ASSOC); 
      
    if (!$position)
    {
      throw new Exception("Can't get Position for Relationship with ID " . $relationship['id']);
    }

    if ($position['is_board'])
    {
      return 'Board Member';
    }
    
    if ($position['is_executive'])
    {
      return 'Executive';
    }
    
    if ($position['is_employee'])
    {
      return 'Employee';
    }

    return null;
  }
}