<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Position extends BasePosition
{
  public function getDetails()
  {
    if ($this->compensation)
    {  
      return 'compensation: $' . $this->compensation;
    }
    
    return null;
  }
  
  
  public function getDisplayDescription($relationship=null)
  {
    return PositionTable::getDisplayDescription($this, $relationship);
  }
}