<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicCompany extends BasePublicCompany
{  
  public function getCik()
  {
    if (!$this->ticker)
    {
      return;
    }

  	$url = 'http://finance.yahoo.com/q/sec?s=' . urlencode($this->ticker) . '+SEC+Filings';
    $cik = null;
    $sic = null;
    $browser = new sfWebBrowser();

  	if (!$browser->get($url)->responseIsError())
  	{
  		$text = $browser->getResponseText();
  
  		//get CIK document codes
  		preg_match('/cik\=(\d+)>/', $text, $matches);

  		if ($matches)
  		{
  			$this->sec_cik = $matches[1];
  			$this->save();
  			return true;
  		}
  	}

  	return false;  		
  }
  
  
  
}