<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfileTable extends Doctrine_Table
{
  static $publicNameChars = 'A-Za-z0-9.';

  static $prohibitedPublicNames = array(
    'entity',
    'list',
    'rel',
    'group'
  );


  static $score_arr = 
    array(
      'Entity' => array(31,22), 
      'Relationship' => array(30,30), 
      'LsList' => array(15,10), 
      'Alias' => array(21,12), 
      'Image' => array(27,17), 
      'Address' => array(15,10)
    );

  public static function getTopUsersQuery($limit = 10, $min = 0, $show_all = false)
  {
    $q = LsDoctrineQuery::create()
        ->from('sfGuardUserProfile p')
        ->leftJoin('p.User u')
        ->where('p.score is not NULL and p.score > ? and u.is_super_admin = ?', array(0,0))
        ->orderBy('p.score DESC');
        
     if (!$show_all)
     {
       $q->addWhere('p.ranking_opt_out = ?', 0);
     }
     return $q;
  }
  
  
  static function getFullName($profile)
  {
    return trim($profile['name_first'] . ' ' . $profile['name_last']);
  }

}