<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{  
  protected $_summary = null;
  
  public function getName()
  {
    return $this->getFullName();
  }

  public function getFullName()
  {
    return trim($this->name_first . ' ' . $this->name_last);
  }
  
  public function refreshScore()
  {
    $mods = LsDoctrineQuery::create()
        ->select('m.object_model,m.is_merge,m.is_create,m.is_delete,count(m.id)')
        ->from('Modification m')
        ->where('m.user_id = ?', $this->user_id)
        ->groupBy('m.object_model,m.is_merge,m.is_create,m.is_delete')
        ->execute();

    $score_arr = sfGuardUserProfileTable::$score_arr;
    $score = 0;

    foreach ($mods as $mod)
    {
      if ($mod->count)
      {
        foreach($score_arr as $k => $v)
        {
          if ($mod->object_model == $k)
          {
            if ($mod->is_create && !$mod->is_merge)
            {
              $score += $v[0] * $mod->count;
            }
            else if (!$mod->is_create && !$mod->is_merge && !$mod->is_delete)
            {
              $score += $v[1] * $mod->count;            
            }
            break;            
          }
        }
      }
    }
    $this->score = $score;
    $this->save();
  }
  
  public function getShortSummary($start = null, $end = null)
  {
    //get count for Images and Relationships
    $models = array('Image' => 0, 'Relationship' => 0, 'Person' => 0, 'Org' => 0);

    $db = Doctrine_Manager::connection();
    $sql = 'SELECT object_model, COUNT(*) num FROM modification WHERE user_id = ? AND is_create = ? AND object_model IN (\'Image\', \'Relationship\') GROUP BY object_model';
    $stmt = $db->execute($sql, array($this->user_id, 1));
    
    foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $model)
    {
      $models[$model['object_model']] = $model['num'];
    }
    

    //get count for People and Organizations
    $sql = 'SELECT object_id FROM modification WHERE user_id = ? AND is_create = ? AND object_model = ?';
    $stmt = $db->execute($sql, array($this->user_id, 1, 'Entity'));    
    $entityIds = $stmt->fetchAll(PDO::FETCH_COLUMN);

    if (count($entityIds))
    {
      $sql = 'SELECT primary_ext, COUNT(*) num FROM entity WHERE id IN (' . implode(',', $entityIds) . ') GROUP BY primary_ext';
      $stmt = $db->execute($sql);
      
      foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $row)
      {
        $models[$row['primary_ext']] = $row['num'];
      }
    }

    arsort($models);
    $this->_summary = $models;

    return $models;
  }  
}