<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends Doctrine_Table
{
  static function getPopularTagsQuery()
  {
    return LsDoctrineQuery::create()
      ->select('t.*, COUNT(ot.id) AS num')
      ->from('Tag t')
      ->leftJoin('t.ObjectTag ot')
      ->where('t.is_visible = ?', true)
      ->groupBy('t.id')
      ->orderBy('num DESC, t.name ASC, t.triple_namespace ASC, t.triple_predicate ASC, t.triple_value ASC');  
  }

  static function getByTripleQuery($namespace, $predicate, $value)
  {
    return LsQuery::getByModelAndFieldsQuery('Tag', array(
      'triple_namespace' => $namespace,
      'triple_predicate' => $predicate,
      'triple_value' => $value
    ));  
  }
}