<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Transaction extends BaseTransaction
{

  public function getDetails()
  {
    $stuff = array();
  
    if ($amount = LsNumber::makeReadable($this->Relationship->amount, '$'))
    {
      $stuff[] = $amount;
    }
    
    if ($this->Relationship->goods)
    {
      $stuff[] = $this->Relationship->goods;
    }
    
    return implode(', ', $stuff);
  }
  
  public function getLobbyingRelationships()
  {
    if ($this->Relationship->Detail->description1 != 'Lobbying')
    {
      return null;
    }        
    else
    {
      $q = RelationshipTable::getByCategoryQuery('Lobbying')
                  ->addWhere('lobbying.lda_filing_id = ?', $this->lda_filing_id)
                  ->execute();
      if (count($q) > 0)
      {
        return $q;
      }
      else
      {
        return null;
      }
    }
  }
  

  public function getLobbyFilingsQuery()
  {
    return Lobbying::getLobbyFilingsByRelationshipIdQuery($this->relationship_id);
  }


  public function countLobbyFilings()
  {
    return $this->getLobbyFilingsQuery()->count();
  }


  public function getLobbyFilingAmountSum()
  {
    return Lobbying::getLobbyFilingAmountSumByRelationshipId($this->relationship_id);
  }
  

  public function addLobbyFiling(LobbyFiling $filing)
  {
    return Lobbying::addLobbyFilingToRelationship($this->Relationship);
  }


  public function getFedspendingFilingAmountSum()
  {
    $ary = LsDoctrineQuery::create()
      ->select('SUM(f.amount) AS sum')
      ->from('FedspendingFiling f')
      ->where('f.relationship_id = ?', $this->relationship_id)
      ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
      ->fetchOne();

    return (int) $ary['sum'];
  }
  
  
  public function getFedspendingFilingsQuery()
  {          
    return Doctrine_Query::create()
      ->from('FedspendingFiling f')
      ->where('f.relationship_id = ?', $this->relationship_id)
      ->orderBy('f.start_date DESC');    
  }


  public function countFedspendingFilings()
  {
    return $this->getFedspendingFilingsQuery()->count();
  }
  
  
  public function addFedspendingFiling(FedspendingFiling $filing)
  {  
    $relationship = $this->Relationship;
    $generatedAmount = $this->getFedspendingFilingAmountSum() + $filing->amount;
    $relationship->amount = max($generatedAmount, $relationship->amount);   
    $relationship->updateDateRange($filing->start_date);
    $relationship->filings = $this->countFedspendingFilings() + 1;
    $relationship->save();          
    
    $filing->relationship_id = $relationship->id;
    $filing->save();
  }


  public function getLobbyingsFromLobbyFiling()
  {
    $q = LsDoctrineQuery::create()
      ->from('Relationship r')
      ->leftJoin('r.LobbyFilingRelationship lfr')
      ->leftJoin('lfr.LobbyFiling lf')
      ->leftJoin('lf.LobbyFilingRelationship lfr2')
      ->andWhere('lfr2.relationship_id = ?', $this->relationship_id)
      ->addWhere('r.id <> ?', $this->relationship_id)
      ->addWhere('r.category_id = ?', RelationshipTable::LOBBYING_CATEGORY);
    
    return $q->execute();
  }
}