<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserFavoriteTable extends Doctrine_Table
{
  static function getByUserIdQuery($userId)
  {
    $q = LsDoctrineQuery::create()
      ->from('UserFavorite f')
      ->where('f.user_id = ? AND f.object_model = ?', array($userId, 'Entity'))
      ->orderBy('f.created_at DESC')
      ->groupBy('f.object_id');
      
    return $q;
  }
  
  
  static function getByUserIdAndObject($userId, Doctrine_Record $object)
  {
    $q = LsDoctrineQuery::create()
      ->from('UserFavorite f')
      ->where('f.user_id = ? AND f.object_model = ? AND f.object_id = ?', array($userId, get_class($object), $object->id));

    return $q->fetchOne();  
  }
}