<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOsEntityPreprocessTable extends Doctrine_Table
{
  static function getCyclesByEntityId($id)
  {
    $db = Doctrine_Manager::connection();
    $sql = 'SELECT cycle FROM os_entity_preprocess WHERE entity_id = ?';
    $stmt = $db->execute($sql, array($id));
    
    return $stmt->fetchAll(PDO::FETCH_COLUMN);
  }
}