<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOsEntityDonorTable extends Doctrine_Table
{
  static function lockEntityById($id, $userId)
  {
    $db = Doctrine_Manager::connection();    
    $sql = 'UPDATE os_entity_donor SET locked_at = ?, locked_by_user_id = ? WHERE entity_id = ?';
    $stmt = $db->execute($sql, array(LsDate::getCurrentDateTime(), $userId, $id));  
  }
  
  
  static function unlockEntityById($id)
  {
    $db = Doctrine_Manager::connection();    
    $sql = 'UPDATE os_entity_donor SET locked_at = NULL, locked_by_user_id = NULL WHERE entity_id = ?';
    $stmt = $db->execute($sql, array($id));
  }


  static function countByEntityId($id)
  {
    $db = Doctrine_Manager::connection();
    $sql = 'SELECT COUNT(*) FROM os_entity_donor WHERE entity_id = ?';
    $stmt = $db->execute($sql, array($id));
    
    return $stmt->fetch(PDO::FETCH_COLUMN);
  }
}