<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOsCategoryTable extends Doctrine_Table
{
  public static $ignoreCategories = array(
    "Y4000", "Y2000", "X1200", "Y1000", "Z9500", "X3000", "J1200", "X0000", "J7400", "J2200", "J1100", "Z9000", "J9100", "Z9100", "Z4100", "Z4200", "J0000", "J1000", "J1300", "J2000", "J3000", "J2300", "J2100", "J2400", "J2500", "J4000", "J5000", "J5100", "J5200", "J6100", "J6200", "J7000", "J7120", "J7150", "J7200", "J7300", "J7400", "J7500", "J7600", "J7700", "J8000", "J9000", "JD100", "JD200", "JE300", "JH100", "Y0000", "Z5100", "Z5200", "Z5300", "Y1000", "Y3000", "Y4000", "Z1100", "Z1200", "X3100", "X3000", "Z1300", "Z9999", "J1110", "Z1000", "Z5000", "Z9600", "J5300", "Z1400", "J7210", "JW100", "J6500", "Z9700", "J5400", "X9000", "Z4300"
  );

  public static $ignoreSectors = array(
    "Candidate",
    "Ideological/Single-Issue",
    "Joint Candidate Cmtes",
    "Non-contribution",
    "Party Cmtes",
    "Unknown"
  );
  
  static function categoryCmp($cat1, $cat2)
  {
    $str1 = $cat1['sector_name'] . $cat1['industry_name'] . $cat1['category_name'];
    $str2 = $cat2['sector_name'] . $cat2['industry_name'] . $cat2['category_name'];

    return strcmp($str1, $str2);
  }
  
  static function getSectorNames()
  {
    $db = LsDb::getDbConnection();
    $sql = "SELECT DISTINCT(sector_name) FROM os_category " . 
          "WHERE sector_name NOT IN('" . join("', '", self::$ignoreSectors) . "') " .
          "ORDER BY sector_name ASC";
    $stmt = $db->execute($sql);
    
    return $stmt->fetchAll(PDO::FETCH_COLUMN);
  }
  
  static function getCategoryIdsFromDonations($donations)
  {
    $codes = array();

    foreach ($donations as $donation)
    {
      if ($code = $donation['industry_id'])
      {
        $codes[strtoupper($code)] = true;
      }      
    }

    return array_keys($codes);  
  }
}