<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOsDonationTable extends Doctrine_Table
{
  static function generateKeyClause($key1, $key2, Array $trans)
  {
    $parts = array();

    foreach ($trans as $tran)
    {
      list($cycle, $transId) = explode(':', $tran);
      $parts[] = sprintf("(%s = '%s' AND %s = '%s')", $key1, $cycle, $key2, $transId);
    }
    
    return implode(' OR ', $parts);
  }
  
  static function buildAddress($donation)
  {
    $ret = $donation['city'] . ', ' . $donation['state'] . ' ' . $donation['zip'];

    if ($donation['street'])
    {
      $ret = $donation['street'] . ', ' . $ret;
    }

    return $ret;
  }
}