<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
  static function getInternalUrl($g, $action=null, Array $params=null)
  {
    if (!is_array($g) && !($g instanceOf sfGuardGroup))
    {
      throw new Exception("Can't get generate route; expecting sfGuardGroup or array");
    }

    if ($action == 'view')
    {
      $action = null;
    }

    $paramStr = '';

    if ($params)
    {
      $params = array_diff_key($params, array_flip(array('name', 'module', 'action')));
    
      $paramStr = http_build_query($params);
      $paramStr = $paramStr ? '&' . $paramStr : null;
    }

    if ($action)
    {
      return '@group?name=' . $g['name'] . '&action=' . $action . $paramStr;
    }
    else
    {
      return '@groupView?name=' . $g['name'] . $paramStr;
    }  
  }
}