<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOsDonationTable extends Doctrine_Table
{

  //produced by querying for common org words in 2012 cycle data  
  static $commonOrgWords = array("", " ", "self", ", ", "employed", " & ", ".", "/", "a", "retired", "n", "inc", "-", "none", "group", "requested", "information", "llc", "of", "llp", "not", "the", ". ", "co", "associates", "capital", "company", "homemaker", "and", "corp", "best", "management", "university", "per", "corporation", "partners", "effo", "law", "bank", "s", "'", "health", "services", "p", "state", "energy", "financial", "medical", "center", "c", "pc", "l", "american", "construction", "international", "consulting", "strategies", "insurance", "enterprises", "city", "hospital", "&", "properties", "companies", "firm", "foundation", "national", "us", "assoc", "investments", "new", "school", "for", "first", "systems", "college", "realty", "industries", "development", "ltd", "na", "america", "care", "o", "advisors", "county", "public", "solutions", "williams", "association", "smith", "united", "j", "service", "holdings", "m", "resources", "capitol", "government", "pa", "healthcare", "communications", "investment", "r", "t", "real", "estate", "clinic", "ventures", "north", "institute", "technologies", "community", "west", "st", "products", "u", "., ", "jones", "efforts", "office", "e", "al",  "family", "d", "et", "global", "strategic", "general", "washington", "agency", "pllc", "florida", "trust", "life", "media", "consultants", "h", "attorney", "southern", "ohio", "at", "affairs", "g", "b", "engineering", "texas", "park", "central", "asset", "mutual", "pacific", "info", "lp",  "senate", "baker", "river", "brothers", "power",  "supply", "equipment", "home", "offices", "system", "k", "homes", "usa", "policy","sales", "business", "technology", "department", " - ",  "relations", "research", "council", "mgmt", "auto",  "w", "virginia",  "farms", "credit","land","dept", "murray", "atlantic", "marketing", "street", "equity", "medicine",  "in", "great", "i", "mortgage", "network", "star", ", & ", "foods", "farm", "fund");
  
  //produced by querying for common title words in 2012 cycle data
  static $commonTitleWords = array("", " ", "retired", "attorney", "president", "requested", "executive", "information", "ceo", "homemaker", "owner", "consultant", "physician", "vice", "director", "manager", "partner", "/", "estate", "real", "chairman", " & ", "best", "per", "investor", "eff", "vp", "engineer", ".", "business", "senior", "sales", "professor", "government", "employed", ", ", "managing", "of", "relations", "principal", "investment", "banker", "lawyer", "-", "farmer", "management", "and", "financial", "affairs", "advisor", "officer", "insurance", "general", ". ", "chief", "investments", "none", "finance", "efforts", "developer", "not", "self", "writer", "cpa", "broker", "teacher", "contractor", "public", "lobbyist", "realtor", "administrator", "agent", "development", "rancher", "cfo", "marketing", "founder", "counsel", "oil", "accountant", "artist", "dentist", "producer", "sr", "surgeon", "coo", "dealer", "gas", "c", "co", "volunteer", "private", "o", "architect", "services", "policy", "student", "a", "analyst", "board", "construction", "e", "assistant", "housewife", "member", "doctor", "exec", "n", "health", "operations", "community", "state", "corporate", " - ", "venture", "info", "designer", "evp", "law", "commercial", "associate", "auto", "svp", "businessman", "nurse", "banking", "scientist", "educator", "psychologist", "candidate", "govt", "pharmacist", "representative", "project", "software", "medical", "office", "equity", "consulting", "philanthropist", "p", "worker", "entrepreneur", "social", "secretary", "care", "the", "property", "professional", "research", "program", "geologist", "retail", "builder", "planner", "specialist", "human", "it", "economist", "'", "healthcare", "trader", "resources", "optometrist", "capital", "mgr", "treasurer", "education", "operating", "v", "therapist", "publisher", "legal", "for", "capitalist", " / ", "chair", "gov", "portfolio", "communications", "counselor", "senator");
  
  static $commonOrgs = array("UNEMPLOYED","INFO REQUESTED", "STUDENT", "NOT EMPLOYED/RETIRED", "RET.", "NONE/RETIRED", "HOUSEWIFE", "HOMEMAKER/HOMEMAKER", "NA", "INFORMATION REQUESTED PER BEST EFFO", "N/A/RETIRED", "REQUESTED", "RETIRED/RETIRED", "HOMEMAKER", "SELF EMPLOYED", "INFORMATION REQUESTED PER BEST EFFORTS", "NOT EMPLOYED", "INFORMATION REQUESTED", "NONE", "N/A", "SELF", "NULL", "SELF-EMPLOYED", "RETIRED","SELF","SELF/LOBBYIST");
  
  
  static function generateKeyClause($key1, $key2, Array $trans)
  {
    $parts = array();

    foreach ($trans as $tran)
    {
      list($cycle, $transId) = explode(':', $tran);
      $parts[] = sprintf("(%s = '%s' AND %s = '%s')", $key1, $cycle, $key2, $transId);
    }
    
    return implode(' OR ', $parts);
  }
  
  static function buildAddress($donation)
  {
    $ret = $donation['city'] . ', ' . $donation['state'] . ' ' . $donation['zip'];

    if ($donation['street'])
    {
      $ret = $donation['street'] . ', ' . $ret;
    }

    return $ret;
  }
}