<?php

class GuessGendersTask extends sfBaseTask
{
  private $db = null;
  private $maleNames = array('JAMES','JOHN','ROBERT','MICHAEL','WILLIAM','DAVID','RICHARD','CHARLES','JOSEPH','THOMAS','CHRISTOPHER','DANIEL','PAUL','MARK','DONALD','GEORGE','KENNETH','STEVEN','EDWARD','BRIAN','RONALD','ANTHONY','KEVIN','JASON','MATTHEW','GARY','TIMOTHY','JOSE','LARRY','JEFFREY','FRANK','SCOTT','ERIC','STEPHEN','ANDREW','RAYMOND','GREGORY','JOSHUA','DENNIS','WALTER','PATRICK','PETER','HAROLD','DOUGLAS','HENRY','CARL','ARTHUR','RYAN','ROGER','JOE','JUAN','JACK','ALBERT','JONATHAN','JUSTIN','GERALD','KEITH','SAMUEL','RALPH','LAWRENCE','NICHOLAS','ROY','BENJAMIN','BRUCE','BRANDON','ADAM','HARRY','FRED','WAYNE','BILLY','STEVE','LOUIS','JEREMY','AARON','RANDY','HOWARD','EUGENE','CARLOS','RUSSELL','BOBBY','VICTOR','MARTIN','ERNEST','PHILLIP','TODD','JESSE','CRAIG','ALAN','CLARENCE','SEAN','PHILIP','JOHNNY','EARL','JIMMY','ANTONIO','DANNY','BRYAN','TONY','LUIS','MIKE','STANLEY','LEONARD','NATHAN','MANUEL','RODNEY','CURTIS','NORMAN','ALLEN','MARVIN','VINCENT','GLENN','JEFFERY','TRAVIS','JEFF','CHAD','JACOB','LEE','MELVIN','ALFRED','KYLE','BRADLEY','JESUS','HERBERT','FREDERICK','RAY','JOEL','EDWIN','DON','RICKY','TROY','RANDALL','BARRY','ALEXANDER','BERNARD','MARIO','LEROY','FRANCISCO','MARCUS','MICHEAL','THEODORE','CLIFFORD','MIGUEL','OSCAR','JAY','JIM','TOM','CALVIN','ALEX','JON','RONNIE','BILL','LLOYD','TOMMY','LEON','DEREK','WARREN','DARRELL','JEROME','FLOYD','LEO','ALVIN','TIM','WESLEY','GORDON','DEAN','GREG','JORGE','DUSTIN','PEDRO','DERRICK','DAN','LEWIS','ZACHARY','COREY','HERMAN','MAURICE','VERNON','ROBERTO','CLYDE','GLEN','HECTOR','SHANE','RICARDO','SAM','RICK','LESTER','BRENT','RAMON','CHARLIE','TYLER','GILBERT','GENE','MARC','REGINALD','RUBEN','BRETT','NATHANIEL','RAFAEL','EDGAR','MILTON','RAUL','BEN','CHESTER','CECIL','DUANE','FRANKLIN','ANDRE','ELMER','BRAD','GABRIEL','RON','MITCHELL','ROLAND','ARNOLD','HARVEY','JARED','KARL','CORY','CLAUDE','ERIK','DARRYL','NEIL','CHRISTIAN','JAVIER','FERNANDO','CLINTON','TED','MATHEW','TYRONE','DARREN','LONNIE','LANCE','CODY','JULIO','KURT','ALLAN','NELSON','GUY','CLAYTON','HUGH','MAX','DWAYNE','DWIGHT','ARMANDO','FELIX','EVERETT','IAN','WALLACE','KEN','BOB','JAIME','ALFREDO','ALBERTO','DAVE','IVAN','SIDNEY','BYRON','JULIAN','ISAAC','MORRIS','CLIFTON','WILLARD','DARYL','ROSS','VIRGIL','ANDY','MARSHALL','SALVADOR','PERRY','KIRK','SERGIO','SETH','KENT','TERRANCE','EDUARDO','TERRENCE','ENRIQUE','FREDDIE','WADE','AUSTIN','STUART','FREDRICK','ARTURO','ALEJANDRO','JOEY','NICK','LUTHER','WENDELL','JEREMIAH','EVAN','JULIUS','DONNIE','OTIS','TREVOR','OLIVER','LUKE','HOMER','GERARD','DOUG','KENNY','HUBERT','ANGELO','SHAUN','LYLE','MATT','ALFONSO','ORLANDO','REX','CARLTON','ERNESTO','CAMERON','NEAL','PABLO','LORENZO','OMAR','WILBUR','BLAKE','GRANT','HORACE','RODERICK','ABRAHAM','WILLIS','RICKEY','IRA','ANDRES','CESAR','JOHNATHAN','MALCOLM','RUDOLPH','DAMON','KELVIN','RUDY','PRESTON','ALTON','ARCHIE','MARCO','WM','PETE','RANDOLPH','GARRY','GEOFFREY','JONATHON','FELIPE','BENNIE','GERARDO','ED','DOMINIC','LOREN','DELBERT','COLIN','GUILLERMO','EARNEST','LUCAS','BENNY','NOEL','SPENCER','RODOLFO','MYRON','EDMUND','GARRETT','SALVATORE','CEDRIC','LOWELL','GREGG','SHERMAN','WILSON','DEVIN','SYLVESTER','ROOSEVELT','ISRAEL','JERMAINE','FORREST','WILBERT','LELAND','SIMON','CLARK','IRVING','CARROLL','BRYANT','OWEN','RUFUS','WOODROW','SAMMY','KRISTOPHER','MACK','LEVI','MARCOS','GUSTAVO','JAKE','LIONEL','MARTY','ELLIS','DALLAS','GILBERTO','CLINT','NICOLAS','LAURENCE','ISMAEL','ORVILLE','DREW','ERVIN','DEWEY','AL','WILFRED','JOSH','HUGO','IGNACIO','CALEB','TOMAS','SHELDON','ERICK','STEWART','DOYLE','DARREL','ROGELIO','TERENCE','SANTIAGO','ALONZO','ELIAS','BERT','ELBERT','RAMIRO','CONRAD','NOAH','GRADY','PHIL','CORNELIUS','LAMAR','ROLANDO','CLAY','PERCY','DEXTER','BRADFORD','MERLE','DARIN','AMOS','TERRELL','MOSES','IRVIN','SAUL','ROMAN','DARNELL','RANDAL','TIMMY','DARRIN','WINSTON','BRENDAN','TOBY','VAN','ABEL','DOMINICK','BOYD','EMILIO','ELIJAH','CARY','DOMINGO','SANTOS','AUBREY','EMMETT','MARLON','EMANUEL','JERALD','EDMOND','EMIL','DEWAYNE','WILL','OTTO','TEDDY','REYNALDO','BRET','JESS','TRENT','HUMBERTO','EMMANUEL','STEPHAN','LOUIE','VICENTE','LAMONT','STACY','GARLAND','MILES','MICAH','EFRAIN','LOGAN','HEATH','RODGER','HARLEY','DEMETRIUS','ETHAN','ELDON','ROCKY','PIERRE','JUNIOR','FREDDY','ELI','BRYCE','ANTOINE','KENDALL','ROYCE','STERLING','MICKEY','CHASE','GROVER','ELTON','CLEVELAND','DYLAN','CHUCK','DAMIAN','REUBEN','STAN','AUGUST','LEONARDO','JASPER','RUSSEL','ERWIN','BENITO','HANS','MONTE','BLAINE','ERNIE','CURT','QUENTIN','AGUSTIN','MURRAY','JAMAL','DEVON','ADOLFO','HARRISON','TYSON','BURTON','BRADY','ELLIOTT','WILFREDO','BART','JARROD','VANCE','DENIS','DAMIEN','JOAQUIN','HARLAN','DESMOND','ELLIOT','DARWIN','GREGORIO','BUDDY','XAVIER','KERMIT','ROSCOE','ESTEBAN','ANTON','SOLOMON','SCOTTY','NORBERT','ELVIN','WILLIAMS','NOLAN','ROD','QUINTON','HAL','BRAIN','ROB','ELWOOD','KENDRICK','DARIUS','MOISES','SON','MARLIN','FIDEL','THADDEUS','CLIFF','MARCEL','ALI','JACKSON','RAPHAEL','BRYON','ARMAND','ALVARO','JEFFRY','DANE','JOESPH','THURMAN','NED','SAMMIE','RUSTY','MICHEL','MONTY','RORY','FABIAN','REGGIE','MASON','GRAHAM','ISAIAH','VAUGHN','GUS','AVERY','LOYD','DIEGO','ADOLPH','NORRIS','MILLARD','ROCCO','GONZALO','DERICK','RODRIGO','GERRY','WILEY','RIGOBERTO','ALPHONSO','TY','RICKIE','NOE','VERN','REED','JEFFERSON','ELVIS','BERNARDO','MAURICIO','HIRAM','DONOVAN','BASIL','RILEY','NICKOLAS','MAYNARD','SCOT','VINCE','QUINCY','EDDY','SEBASTIAN','FEDERICO','ULYSSES','HERIBERTO','DONNELL','COLE','DENNY','DAVIS','GAVIN','EMERY','WARD','ROMEO','JAYSON','DION','DANTE','CLEMENT','COY','ODELL','MAXWELL','JARVIS','BRUNO','ISSAC','DUDLEY','BROCK','SANFORD','COLBY','CARMELO','BARNEY','NESTOR','HOLLIS','STEFAN','DONNY','ART','LINWOOD','BEAU','WELDON','GALEN','ISIDRO','TRUMAN','DELMAR','JOHNATHON','SILAS','FREDERIC','DICK','KIRBY','IRWIN','CRUZ','MERLIN','MERRILL','CHARLEY','MARCELINO','LANE','HARRIS','CARLO','TRENTON','KURTIS','HUNTER','AURELIO','WINFRED','VITO','COLLIN','DENVER','CARTER','LEONEL','EMORY','PASQUALE','MOHAMMAD','MARIANO','DANIAL','BLAIR','LANDON','DIRK','BRANDEN','ADAN','NUMBERS','CLAIR','BUFORD','GERMAN','BERNIE','WILMER','EMERSON','ZACHERY','FLETCHER','JACQUES','ERROL','DALTON','MONROE','JOSUE','EDWARDO','BOOKER','WILFORD','SONNY','SHELTON','CARSON','THERON','RAYMUNDO','DAREN','TRISTAN','HOUSTON','ROBBY','LINCOLN','JAME','GENARO','BENNETT','OCTAVIO','CORNELL','HUNG','ARRON','ANTONY','HERSCHEL','ALVA','GIOVANNI','GARTH','CYRUS','CYRIL','RONNY','STEVIE','LON','FREEMAN','DUNCAN','KENNITH','CARMINE','AUGUSTINE','ERICH','CHADWICK','WILBURN','RUSS','REID','MYLES','ANDERSON','MORTON','JONAS','FOREST','MITCHEL','MERVIN','ZANE','RICH','JAMEL','LAZARO','ALPHONSE','RANDELL','MAJOR','JOHNIE','JARRETT','BROOKS','ARIEL','ABDUL','DUSTY','LUCIANO','SEYMOUR','SCOTTIE','EUGENIO','MOHAMMED','VALENTIN','CHANCE','ARNULFO','LUCIEN','FERDINAND','THAD','EZRA','SYDNEY','ALDO','RUBIN','ROYAL','MITCH','EARLE','ABE','WYATT','MARQUIS','LANNY','KAREEM','JAMAR','BORIS','ISIAH','EMILE','ELMO','ARON','LEOPOLDO','EVERETTE','JOSEF','ELOY','DORIAN','RODRICK','REINALDO','LUCIO','JERROD','WESTON','HERSHEL','BARTON','PARKER','LEMUEL','LAVERN','BURT','JULES','GIL','ELISEO','AHMAD','NIGEL','EFREN','ANTWAN','ALDEN','MARGARITO','COLEMAN','REFUGIO','DINO','OSVALDO','LES','DEANDRE','NORMAND','KIETH','IVORY','TREY','NORBERTO','NAPOLEON','JEROLD','FRITZ','ROSENDO','MILFORD','SANG','DEON','CHRISTOPER','ALFONZO','LYMAN','JOSIAH','BRANT','WILTON','RICO','JAMAAL','DEWITT','BRENTON','YONG','OLIN','FOSTER','FAUSTINO','CLAUDIO','JUDSON','GINO','EDGARDO','BERRY','ALEC','TANNER','JARRED','DONN','TRINIDAD','TAD','PRINCE','PORFIRIO','ODIS','LENARD','CHAUNCEY','CHANG','TOD','MEL','MARCELO','KORY','AUGUSTUS','KEVEN','HILARIO','BUD','SAL','ORVAL','MAURO','DANNIE','ZACHARIAH','OLEN','ANIBAL','MILO','JED','THANH','DILLON','AMADO','NEWTON','LENNY','TORY','RICHIE','HORACIO','BRICE','MOHAMED','DELMER','DARIO','REYES','MAC','JONAH','JERROLD','ROBT','HANK','SUNG','RUPERT','ROLLAND','KENTON','DAMION','CHI','ANTONE','WALDO','FREDRIC','BRADLY','QUINN','KIP','BURL','WALKER','TYREE','JEFFEREY','AHMED','WILLY','STANFORD','OREN','NOBLE','MOSHE','MIKEL','ENOCH','BRENDON','QUINTIN','JAMISON','FLORENCIO','DARRICK','TOBIAS','MINH','HASSAN','GIUSEPPE','DEMARCUS','CLETUS','TYRELL','LYNDON','KEENAN','WERNER','THEO','GERALDO','COLUMBUS','CHET','BERTRAM','MARKUS','HUEY','HILTON','DWAIN','DONTE','TYRON','OMER','ISAIAS','HIPOLITO','FERMIN','CHUNG','ADALBERTO','VALENTINE','JAMEY','BO','BARRETT','TEODORO','MCKINLEY','MAXIMO','GARFIELD','SOL','RALEIGH','LAWERENCE','ABRAM','RASHAD','KING','EMMITT','DARON','CHONG','SAMUAL','PARIS','OTHA','MIQUEL','EUSEBIO','DONG','DOMENIC','DARRON','BUSTER','WILBER','RENATO','JC','HOYT','HAYWOOD','EZEKIEL','CHAS','FLORENTINO','ELROY','CLEMENTE','ARDEN','NEVILLE','EDISON','DESHAWN','CARROL','SHAYNE','NATHANIAL','JORDON','DANILO','CLAUD','VAL','SHERWOOD','RAYMON','RAYFORD','CRISTOBAL','AMBROSE','TITUS','HYMAN','FELTON','EZEQUIEL','ERASMO','STANTON','LONNY','LEN','IKE','MILAN','LINO','JAROD','HERB','ANDREAS','WALTON','RHETT','PALMER','JUDE','DOUGLASS','CORDELL','OSWALDO','ELLSWORTH','VIRGILIO','TONEY','NATHANAEL','DEL','BRITT','BENEDICT','MOSE','HONG','JOHNSON','ISREAL','GARRET','FAUSTO','ASA','ARLEN','ZACK','WARNER','MODESTO','FRANCESCO','MANUAL','JAE','GAYLORD','GASTON','FILIBERTO','DEANGELO','MICHALE','GRANVILLE','WES','MALIK','ZACKARY','TUAN','NICKY','ELDRIDGE','CRISTOPHER','CORTEZ','ANTIONE','MALCOM','LONG','KOREY','JOSPEH','COLTON','WAYLON','VON','HOSEA','SHAD','SANTO','RUDOLF','ROLF','REY','RENALDO','MARCELLUS','LUCIUS','KRISTOFER','BOYCE','BENTON','MAN','HAYDEN','HARLAND','ARNOLDO','RUEBEN','LEANDRO','KRAIG','JERRELL','JEROMY','HOBERT','CEDRICK','ARLIE','WINFORD','WALLY','LUIGI','KENETH','JACINTO','GRAIG','FRANKLYN','EDMUNDO','SID','PORTER','LEIF','JERAMY','ELISHA','BUCK','WILLIAN','VINCENZO','SHON','MICHAL','LYNWOOD','LINDSAY','JERE','HAI','ELDEN','DORSEY','DARELL','BRODERICK','ALONSO');
  private $femaleNames = array('MARY','PATRICIA','LINDA','BARBARA','ELIZABETH','JENNIFER','MARIA','SUSAN','MARGARET','DOROTHY','LISA','NANCY','KAREN','BETTY','HELEN','SANDRA','DONNA','CAROL','RUTH','SHARON','MICHELLE','LAURA','SARAH','KIMBERLY','DEBORAH','JESSICA','CYNTHIA','ANGELA','MELISSA','BRENDA','AMY','ANNA','REBECCA','VIRGINIA','KATHLEEN','PAMELA','MARTHA','DEBRA','AMANDA','STEPHANIE','CAROLYN','CHRISTINE','MARIE','JANET','CATHERINE','ANN','JOYCE','DIANE','ALICE','JULIE','HEATHER','TERESA','DORIS','GLORIA','EVELYN','CHERYL','MILDRED','KATHERINE','JOAN','JUDITH','ROSE','JANICE','NICOLE','JUDY','CHRISTINA','KATHY','THERESA','BEVERLY','DENISE','TAMMY','IRENE','JANE','LORI','RACHEL','MARILYN','ANDREA','KATHRYN','LOUISE','SARA','ANNE','JACQUELINE','WANDA','BONNIE','JULIA','RUBY','LOIS','TINA','PHYLLIS','NORMA','PAULA','DIANA','ANNIE','LILLIAN','EMILY','PEGGY','CRYSTAL','GLADYS','RITA','DAWN','FLORENCE','EDNA','TIFFANY','ROSA','CINDY','GRACE','WENDY','VICTORIA','EDITH','SHERRY','SYLVIA','JOSEPHINE','THELMA','SHEILA','ETHEL','ELLEN','ELAINE','MARJORIE','CARRIE','CHARLOTTE','MONICA','ESTHER','PAULINE','EMMA','JUANITA','ANITA','RHONDA','HAZEL','AMBER','EVA','DEBBIE','APRIL','CLARA','LUCILLE','JOANNE','ELEANOR','VALERIE','DANIELLE','MEGAN','ALICIA','SUZANNE','MICHELE','BERTHA','DARLENE','VERONICA','JILL','GERALDINE','CATHY','JOANN','LORRAINE','SALLY','REGINA','ERICA','BEATRICE','DOLORES','BERNICE','AUDREY','YVONNE','ANNETTE','JUNE','SAMANTHA','MARION','STACY','ANA','RENEE','IDA','VIVIAN','ROBERTA','HOLLY','BRITTANY','MELANIE','LORETTA','YOLANDA','JEANETTE','LAURIE','KATIE','KRISTEN','VANESSA','ALMA','SUE','ELSIE','BETH','JEANNE','VICKI','CARLA','TARA','ROSEMARY','EILEEN','TERRI','GERTRUDE','LUCY','TONYA','ELLA','WILMA','GINA','KRISTIN','NATALIE','AGNES','VERA','CHARLENE','BESSIE','DELORES','MELINDA','PEARL','ARLENE','MAUREEN','COLLEEN','ALLISON','TAMARA','JOY','GEORGIA','CONSTANCE','LILLIE','CLAUDIA','MARCIA','TANYA','NELLIE','MINNIE','MARLENE','HEIDI','GLENDA','LYDIA','VIOLA','MARIAN','STELLA','CAROLINE','DORA','JO','VICKIE','MATTIE','MAXINE','IRMA','MABEL','MARSHA','MYRTLE','LENA','CHRISTY','DEANNA','PATSY','HILDA','GWENDOLYN','JENNIE','NORA','MARGIE','NINA','CASSANDRA','LEAH','PENNY','KAY','PRISCILLA','NAOMI','CAROLE','BRANDY','OLGA','DIANNE','LEONA','JENNY','FELICIA','SONIA','MIRIAM','VELMA','BECKY','VIOLET','KRISTINA','TONI','MISTY','MAE','SHELLY','DAISY','RAMONA','SHERRI','ERIKA','KATRINA','CLAIRE','LINDSAY','GENEVA','BELINDA','MARGARITA','SHERYL','CORA','FAYE','ADA','NATASHA','SABRINA','ISABEL','MARGUERITE','HATTIE','HARRIET','MOLLY','CECILIA','KRISTI','BRANDI','BLANCHE','ROSIE','JOANNA','IRIS','EUNICE','ANGIE','INEZ','LYNDA','MADELINE','AMELIA','ALBERTA','GENEVIEVE','MONIQUE','JODI','JANIE','MAGGIE','KAYLA','SONYA','LEE','KRISTINE','CANDACE','FANNIE','MARYANN','OPAL','ALISON','YVETTE','MELODY','LUZ','SUSIE','OLIVIA','FLORA','SHELLEY','KRISTY','MAMIE','LULA','LOLA','VERNA','BEULAH','ANTOINETTE','CANDICE','JUANA','JEANNETTE','PAM','KELLI','HANNAH','BRIDGET','KARLA','CELIA','LATOYA','PATTY','SHELIA','DELLA','VICKY','LYNNE','SHERI','MARIANNE','KARA','JACQUELYN','ERMA','BLANCA','MYRA','LETICIA','KRISTA','ROXANNE','ANGELICA','ROBYN','ADRIENNE','ROSALIE','ALEXANDRA','BROOKE','BETHANY','SADIE','BERNADETTE','TRACI','KENDRA','JASMINE','NICHOLE','RACHAEL','CHELSEA','MABLE','ERNESTINE','MURIEL','MARCELLA','ELENA','KRYSTAL','ANGELINA','NADINE','KARI','ESTELLE','DIANNA','PAULETTE','LORA','MONA','DOREEN','ROSEMARIE','DESIREE','HOPE','GINGER','JANIS','BETSY','CHRISTIE','FREDA','MERCEDES','MEREDITH','LYNETTE','TERI','CRISTINA','EULA','MEGHAN','SOPHIA','ELOISE','ROCHELLE','GRETCHEN','CECELIA','RAQUEL','HENRIETTA','ALYSSA','JANA','GWEN','JENNA','TRICIA','OLIVE','TASHA','SILVIA','ELVIRA','DELIA','SOPHIE','KATE','PATTI','LORENA','KELLIE','SONJA','LILA','LANA','DARLA','MAY','MINDY','ESSIE','MANDY','LORENE','ELSA','JOSEFINA','JEANNIE','MIRANDA','DIXIE','LUCIA','MARTA','FAITH','LELA','JOHANNA','SHARI','CAMILLE','TAMI','SHAWNA','ELISA','EBONY','MELBA','ORA','NETTIE','TABITHA','JAIME','WINIFRED','KRISTIE','MARINA','ALISHA','AIMEE','RENA','MYRNA','MARLA','TAMMIE','LATASHA','BONITA','PATRICE','RONDA','SHERRIE','ADDIE','FRANCINE','DELORIS','STACIE','ADRIANA','CHERI','ABIGAIL','CELESTE','CARA','ADELE','REBEKAH','LUCINDA','DORTHY','EFFIE','TRINA','REBA','SALLIE','AURORA','LENORA','ETTA','LOTTIE','KERRI','TRISHA','NIKKI','ESTELLA','FRANCISCA','JOSIE','TRACIE','MARISSA','KARIN','BRITTNEY','JANELLE','LOURDES','LAUREL','HELENE','FERN','ELVA','CORINNE','KELSEY','INA','BETTIE','ELISABETH','AIDA','CAITLIN','INGRID','IVA','EUGENIA','CHRISTA','GOLDIE','CASSIE','MAUDE','JENIFER','THERESE','DENA','LORNA','JANETTE','LATONYA','CANDY','CONSUELO','TAMIKA','ROSETTA','DEBORA','CHERIE','POLLY','DINA','FAY','JILLIAN','DOROTHEA','NELL','TRUDY','ESPERANZA','PATRICA','KIMBERLEY','SHANNA','HELENA','CAROLINA','STEFANIE','OLA','JANINE','MOLLIE','ALISA','MARIBEL','SUSANNE','BETTE','SUSANA','ELISE','CECILE','ISABELLE','JOCELYN','PAIGE','JONI','RACHELLE','LEOLA','DAPHNE','ALTA','ESTER','PETRA','GRACIELA','IMOGENE','JOLENE','KEISHA','LACEY','GLENNA','GABRIELA','KERI','URSULA','LIZZIE','KIRSTEN','SHANA','ADELINE','MAYRA','JAYNE','JACLYN','GRACIE','SONDRA','CARMELA','MARISA','ROSALIND','CHARITY','TONIA','BEATRIZ','MARISOL','CLARICE','JEANINE','SHEENA','ANGELINE','FRIEDA','LILY','SHAUNA','MILLIE','CLAUDETTE','CATHLEEN','ANGELIA','GABRIELLE','AUTUMN','KATHARINE','SUMMER','JODIE','STACI','LEA','CHRISTI','JUSTINE','ELMA','LUELLA','MARGRET','SOCORRO','MARTINA','MARGO','MAVIS','CALLIE','BOBBI','MARITZA','LUCILE','LEANNE','JEANNINE','DEANA','AILEEN','LORIE','LADONNA','WILLA','MANUELA','SELMA','DOLLY','SYBIL','ABBY','LARA','IVY','WINNIE','MARCY','LUISA','JERI','MAGDALENA','OFELIA','MEAGAN','AUDRA','MATILDA','LEILA','CORNELIA','BIANCA','SIMONE','BETTYE','RANDI','VIRGIE','LATISHA','BARBRA','GEORGINA','ELIZA','LEANN','BRIDGETTE','RHODA','HALEY','ADELA','NOLA','BERNADINE','FLOSSIE','ILA','GRETA','RUTHIE','NELDA','MINERVA','LILLY','TERRIE','LETHA','HILARY','ESTELA','VALARIE','BRIANNA','ROSALYN','EARLINE','CATALINA','AVA','MIA','CLARISSA','LIDIA','CORRINE','ALEXANDRIA','CONCEPCION','TIA','SHARRON','RAE','DONA','ERICKA','JAMI','ELNORA','CHANDRA','LENORE','NEVA','MARYLOU','MELISA','TABATHA','SERENA','AVIS','ALLIE','SOFIA','JEANIE','ODESSA','NANNIE','HARRIETT','LORAINE','PENELOPE','MILAGROS','EMILIA','BENITA','ALLYSON','ASHLEE','TANIA','ESMERALDA','KARINA','EVE','PEARLIE','ZELMA','MALINDA','NOREEN','TAMEKA','SAUNDRA','HILLARY','AMIE','ALTHEA','ROSALINDA','LILIA','ALANA','GAY','CLARE','ALEJANDRA','ELINOR','LORRIE','JERRI','DARCY','EARNESTINE','CARMELLA','NOEMI','MARCIE','LIZA','ANNABELLE','LOUISA','EARLENE','MALLORY','CARLENE','NITA','SELENA','TANISHA','KATY','JULIANNE','LAKISHA','EDWINA','MARICELA','MARGERY','KENYA','DOLLIE','ROXIE','ROSLYN','KATHRINE','NANETTE','CHARMAINE','LAVONNE','ILENE','TAMMI','SUZETTE','CORINE','KAYE','MERLE','CHRYSTAL','LINA','DEANNE','LILIAN','JULIANA','ALINE','LUANN','MARYANNE','EVANGELINE','COLETTE','MELVA','LAWANDA','YESENIA','NADIA','MADGE','KATHIE','OPHELIA','VALERIA','NONA','MITZI','MARI','GEORGETTE','CLAUDINE','FRAN','ALISSA','ROSEANN','LAKEISHA','SUSANNA','REVA','DEIDRE','CHASITY','SHEREE','CARLY','ELVIA','ALYCE','DEIRDRE','GENA','BRIANA','ARACELI','KATELYN','ROSANNE','WENDI','TESSA','BERTA','MARVA','IMELDA','MARIETTA','MARCI','LEONOR','ARLINE','SASHA','MADELYN','JANNA','JULIETTE','DEENA','AURELIA','JOSEFA','AUGUSTA','LILIANA','CHRISTIAN','LESSIE','AMALIA','SAVANNAH','ANASTASIA','VILMA','NATALIA','ROSELLA','LYNNETTE','CORINA','ALFREDA','LEANNA','AMPARO','COLEEN','TAMRA','AISHA','WILDA','KARYN','CHERRY','QUEEN','MAURA','MAI','EVANGELINA','ROSANNA','HALLIE','ERNA','ENID','MARIANA','JULIET','JACKLYN','FREIDA','MADELEINE','MARA','HESTER','CATHRYN','LELIA','CASANDRA','BRIDGETT','ANGELITA','JANNIE','DIONNE','ANNMARIE','KATINA','BERYL','PHOEBE','MILLICENT','KATHERYN','DIANN','CARISSA','MARYELLEN','LIZ','LAURI','HELGA','GILDA','RHEA','MARQUITA','HOLLIE','TISHA','TAMERA','ANGELIQUE','FRANCESCA','BRITNEY','KAITLIN','LOLITA','FLORINE','ROWENA','REYNA','TWILA','FANNY','JANELL','INES','CONCETTA','BERTIE','ALBA','BRIGITTE','ALYSON','VONDA','PANSY','ELBA','NOELLE','LETITIA','KITTY','DEANN','BRANDIE','LOUELLA','LETA','FELECIA','SHARLENE','LESA','BEVERLEY','ISABELLA','HERMINIA','TERRA','CELINA');


  protected function configure()
  {
    $this->namespace        = 'cleanup';
    $this->name             = 'guess-genders';
    $this->briefDescription = 'Guesses a gender for people without one';
    $this->detailedDescription = '';
		
    $this->addArgument('application', null, 'The application', 'frontend');
    $this->addOption('env', null, sfCommandOption::PARAMETER_REQUIRED, 'The environment', 'prod');
    $this->addOption('debug_mode', null, sfCommandOption::PARAMETER_REQUIRED, 'Show debugging info', false);
    $this->addOption('test_mode', null, sfCommandOption::PARAMETER_REQUIRED, 'Save changes', false);
    $this->addOption('limit', null, sfCommandOption::PARAMETER_REQUIRED, 'Maximum number of whatevers to whatever', 1000);
  }


  protected function execute($arguments = array(), $options = array())
  {
    $configuration = ProjectConfiguration::getApplicationConfiguration($arguments['application'], $options['env'], true); 
    $databaseManager = new sfDatabaseManager($configuration);
    $databaseManager->initialize($configuration);

    $this->db = Doctrine_Manager::connection();
    $time = microtime(true);
    $listId = 110;

    //get TheyRule people without genders
    $sql = 'SELECT DISTINCT e.name, r.entity1_id AS id, e.summary, p2.name_first ' .
           'FROM ls_list_entity le ' .
           'LEFT JOIN relationship r ON (r.entity2_id = le.entity_id) ' .
           'LEFT JOIN position p ON (p.relationship_id = r.id) ' .
           'LEFT JOIN entity e ON (e.id = r.entity1_id) ' .
           'LEFT JOIN person p2 ON (p2.entity_id = r.entity1_id) ' .
           'WHERE le.list_id = ? ' .
           'AND r.category_id = 1 AND r.is_deleted = 0 ' .
           'AND (p.is_executive = 1 OR p.is_board = 1) ' .
           'AND p2.gender_id IS NULL ' . 
           'AND e.primary_ext = ? AND e.is_deleted = 0 ' .
           'LIMIT ' . $options['limit'];

    $stmt = $this->db->execute($sql, array($listId, 'Person'));
    $entities = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $unknownNum = 0;
    $unknowns = array();

    foreach ($entities as $entity)
    {
      $name = $entity['name_first'];
      $gender = '?';
      
      if (in_array(strtoupper($name), $this->femaleNames))
      {
        $gender = 'F';
      }
      elseif (in_array(strtoupper($name), $this->maleNames))
      {
        $gender = 'M';
      }
      elseif ($entity['summary'])
      {
        if (strpos($entity['summary'], 'Mrs.') === 0)
        {
          $gender = 'F';
        }
        elseif (strpos($entity['summary'], 'Ms.') === 0)
        {
          $gender = 'F';        
        }
        elseif (strpos($entity['summary'], 'Mr.') === 0)
        {
          $gender = 'M';        
        }
        else
        {
          $femaleRegex = '#[\s.,;-](she|her|ms|mrs)[\s.,;-]#i';
          $maleRegex = '#[\s.,;](he|his|him|mr)[\s.,;]#i';
          
          $femaleCount = preg_match_all($femaleRegex, $entity['summary'], $femaleMatches);
          $maleCount = preg_match_all($maleRegex, $entity['summary'], $maleMatches);
          
          if ($femaleCount > 1 && !$maleCount)
          {
            $gender = 'F';
          }
          elseif ($maleCount > 1 && !$femaleCount)
          {
            $gender = 'M';
          }
        }        
      }

      $genderIds = array(
        'F' => 1,
        'M' => 2,
        '?' => NULL
      );

      if ($genderId = $genderIds[$gender])
      {
        $sql = 'UPDATE person SET gender_id = ? WHERE entity_id = ?';
        $stmt = $this->db->execute($sql, array($genderId, $entity['id']));
      }
      else
      {
        $unknownNum++;
        $unknowns[] = $entity['id'];
      }

      if ($options['debug_mode'])
      {
        print($gender . ": " . $entity['name'] . "\n");
      }
    }


    //write unknowns to queue
    if (count($unknowns))
    {
      $sql = 'INSERT IGNORE INTO theyrule_gender_queue (entity_id) VALUES (' . implode('),(', $unknowns) . ')';
      $stmt = $this->db->execute($sql);
    }


    $elapsedTime = microtime(true) - $time;    
    print("Processed " . count($entities) . " people in " . $elapsedTime . " s\n");
    print(count($unknowns) . " people with unknown gender written to queue \n");
  }
}